import React, { useState, useEffect } from 'react';
import { submitAnswer, generateQuestion } from '../services/questionService';
import LoadingSpinner from '../components/LoadingSpinner';
// import ErrorMessage from '../components/ErrorMessage';
import { FaLightbulb, FaRedo, FaTrash } from 'react-icons/fa';
import { getCategoryName } from '../utils/formatters';
import './Practice.css';

/**
 * Practice Page - Expert-curated logic questions
 */
const Practice = () => {
    const [category, setCategory] = useState('number-series');
    const [difficulty, setDifficulty] = useState('easy');
    const [question, setQuestion] = useState(null);
    const [selectedAnswer, setSelectedAnswer] = useState('');
    const [showResult, setShowResult] = useState(false);
    const [result, setResult] = useState(null);
    const [explanation, setExplanation] = useState('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');
    const [autoGenerate, setAutoGenerate] = useState(true);
    const [autoGenerateDelay, setAutoGenerateDelay] = useState(3);
    const [totalQuestionsGenerated, setTotalQuestionsGenerated] = useState(0);
    const [timer, setTimer] = useState(null);
    const [countdown, setCountdown] = useState(0);

    // Clean up timer on unmount
    useEffect(() => {
        return () => {
            if (timer) clearTimeout(timer);
        };
    }, [timer]);

    // Cleanup timer on unmount
    useEffect(() => {
        return () => {
            if (timer) clearTimeout(timer);
        };
    }, [timer]);

    // Handle countdown for auto-generate
    useEffect(() => {
        let interval;
        if (countdown > 0) {
            interval = setInterval(() => {
                setCountdown(prev => prev - 1);
            }, 1000);
        }
        return () => clearInterval(interval);
    }, [countdown]);

    const categories = [
        { value: 'number-series', label: 'Number Series' },
        { value: 'patterns', label: 'Patterns' },
        { value: 'puzzles', label: 'Puzzles' },
        { value: 'aptitude', label: 'Aptitude' },
        { value: 'reasoning', label: 'Reasoning' },
        { value: 'boolean-logic', label: 'Boolean Logic' },
        { value: 'algorithmic-logic', label: 'Algorithmic Logic' }
    ];

    const difficulties = [
        { value: 'easy', label: 'Easy' },
        { value: 'medium', label: 'Medium' },
        { value: 'hard', label: 'Hard' }
    ];

    const handleReset = () => {
        setTotalQuestionsGenerated(0);
        setQuestion(null);
        setError('');
    };

    const handleGenerateQuestion = async () => {
        setError('');
        setLoading(true);
        setQuestion(null);
        setSelectedAnswer('');
        setShowResult(false);
        setExplanation('');

        try {
            // Use level from user or difficulty from selector
            // For now, using difficulty from selector directly
            const response = await generateQuestion(category, null, difficulty);
            setQuestion(response.data);
            setTotalQuestionsGenerated(totalQuestionsGenerated + 1);
        } catch (err) {
            setError(err.response?.data?.message || 'Failed to fetch question. Please try again.');
        } finally {
            setLoading(false);
        }
    };

    // Removed handleGetHint logic as per simplified static bank approach

    const handleSubmitAnswer = async () => {
        if (!selectedAnswer) {
            setError('Please select an answer');
            return;
        }

        setLoading(true);
        try {
            const response = await submitAnswer(question._id, selectedAnswer);
            setResult(response.data);
            setShowResult(true);

            // Explanation is now returned directly from the submitAnswer endpoint (saved in DB)
            setExplanation(response.data.explanation);

            // Auto-generate next question after delay
            if (autoGenerate) {
                setCountdown(autoGenerateDelay);
                const newTimer = setTimeout(() => {
                    handleGenerateQuestion();
                    setTimer(null);
                    setCountdown(0);
                }, autoGenerateDelay * 1000);
                setTimer(newTimer);
            }
        } catch (err) {
            setError('Failed to submit answer');
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="practice-page">
            <div className="container">
                <div className="practice-header text-center mb-lg">
                    <h1 className="text-gradient">Training Grounds</h1>
                    <p className="text-secondary">Refine your neurons with targeted cognitive resistance.</p>
                </div>

                {/* Settings */}
                <div className="practice-settings card">
                    <div className="settings-row">
                        <div className="input-group">
                            <label>Category</label>
                            <select value={category} onChange={(e) => setCategory(e.target.value)}>
                                {categories.map(cat => (
                                    <option key={cat.value} value={cat.value}>{cat.label}</option>
                                ))}
                            </select>
                        </div>

                        <div className="input-group">
                            <label>Difficulty</label>
                            <select value={difficulty} onChange={(e) => setDifficulty(e.target.value)}>
                                {difficulties.map(diff => (
                                    <option key={diff.value} value={diff.value}>{diff.label}</option>
                                ))}
                            </select>
                        </div>

                        <div className="input-group">
                            <label>
                                <input
                                    type="checkbox"
                                    checked={autoGenerate}
                                    onChange={(e) => setAutoGenerate(e.target.checked)}
                                />
                                Auto-generate next question
                            </label>
                        </div>

                        {autoGenerate && (
                            <div className="input-group">
                                <label>Delay (seconds): {autoGenerateDelay}s</label>
                                <input
                                    type="range"
                                    min="1"
                                    max="10"
                                    value={autoGenerateDelay}
                                    onChange={(e) => setAutoGenerateDelay(Number(e.target.value))}
                                />
                            </div>
                        )}

                        <button
                            onClick={() => {
                                if (timer) clearTimeout(timer);
                                setTimer(null);
                                setCountdown(0);
                                handleGenerateQuestion();
                            }}
                            className="btn btn-primary"
                            disabled={loading}
                        >
                            <FaRedo /> New Session
                        </button>
                    </div>
                </div>

                {/* Error Message */}
                {error && (
                    <div className="error-message card fade-in" style={{ backgroundColor: 'rgba(255, 0, 0, 0.1)', border: '1px solid #ff4444', color: '#ff4444', padding: '1rem', marginBottom: '1rem' }}>
                        <p>{error}</p>
                        <button onClick={handleGenerateQuestion} className="btn btn-secondary mt-sm">Retry</button>
                    </div>
                )}

                {loading && !question && <LoadingSpinner message="Generating question..." />}

                {/* Question Display */}
                {question && (
                    <div className="question-card glass-card fade-in">
                        <div className="question-meta mb-lg">
                            <span className="badge badge-primary">{getCategoryName(category)}</span>
                            <span className="badge badge-success">{difficulty}</span>
                            <span className="text-glow ml-auto">{question.points} XP Available</span>
                        </div>

                        <h2 className="question-text">{question.questionText}</h2>

                        <div className="options-list">
                            {question.options.map((option, index) => (
                                <div
                                    key={index}
                                    className={`option-item ${selectedAnswer === option ? 'selected' : ''} ${showResult ? (option === result.correctAnswer ? 'correct' : selectedAnswer === option ? 'incorrect' : '') : ''
                                        }`}
                                    onClick={() => !showResult && setSelectedAnswer(option)}
                                >
                                    <span className="option-label">{String.fromCharCode(65 + index)}</span>
                                    <span className="option-text">{option}</span>
                                </div>
                            ))}
                        </div>

                        {!showResult && (
                            <div className="question-actions mt-lg">
                                <button
                                    onClick={handleSubmitAnswer}
                                    className="btn btn-primary btn-full"
                                    disabled={!selectedAnswer || loading}
                                >
                                    Verify Solution
                                </button>
                            </div>
                        )}

                        {/* Result */}
                        {showResult && (
                            <div className={`result-box ${result.isCorrect ? 'correct' : 'incorrect'}`}>
                                <h3>{result.isCorrect ? '✓ Correct!' : '✗ Incorrect'}</h3>
                                {result.isCorrect && <p>You earned {result.pointsEarned} points!</p>}
                                {result.levelUp && (
                                    <div className="level-up-notice pulse">
                                        <h4>🎊 LEVEL UP! 🎊</h4>
                                        <p>You've reached Level {result.newLevel}!</p>
                                    </div>
                                )}
                                {!result.isCorrect && <p>The correct answer was: {result.correctAnswer}</p>}

                                {explanation && (
                                    <div className="explanation-box">
                                        <h4>Explanation:</h4>
                                        <p>{explanation}</p>
                                    </div>
                                )}

                                {autoGenerate && (
                                    <p className="auto-generate-notice">
                                        <span className="spinner"></span> Next question loading in {countdown}s...
                                    </p>
                                )}

                                {!autoGenerate && (
                                    <button onClick={handleGenerateQuestion} className="btn btn-primary mt-md">
                                        <FaRedo /> Try Another Question
                                    </button>
                                )}
                            </div>
                        )}
                    </div>
                )}

                {!question && !loading && (
                    <div className="empty-state card text-center">
                        <h3>Ready to Practice?</h3>
                        <p>Select a category and difficulty level, then generate a question to get started!</p>
                    </div>
                )}
            </div>
        </div>
    );
};

export default Practice;
