/**
 * Comprehensive Question Bank - 500+ total questions
 * Easy: 215 questions, Medium: 220 questions, Hard: 140 questions
 * Categories: number-series, patterns, puzzles, aptitude, reasoning
 */

const easyQuestions = [
  // EASY - NUMBER SERIES (80 questions)
  { num: [2, 4, 6, 8], next: '10', desc: 'Add 2 each time', category: 'number-series' },
  { num: [5, 10, 15, 20], next: '25', desc: 'Add 5 each time', category: 'number-series' },
  { num: [1, 3, 5, 7], next: '9', desc: 'Add 2 (odd numbers)', category: 'number-series' },
  { num: [10, 20, 30, 40], next: '50', desc: 'Add 10 each time', category: 'number-series' },
  { num: [3, 6, 9, 12], next: '15', desc: 'Add 3 each time', category: 'number-series' },
  { num: [7, 14, 21, 28], next: '35', desc: 'Add 7 each time', category: 'number-series' },
  { num: [100, 90, 80, 70], next: '60', desc: 'Subtract 10 each time', category: 'number-series' },
  { num: [50, 45, 40, 35], next: '30', desc: 'Subtract 5 each time', category: 'number-series' },
  { num: [12, 10, 8, 6], next: '4', desc: 'Subtract 2 each time', category: 'number-series' },
  { num: [25, 20, 15, 10], next: '5', desc: 'Subtract 5 each time', category: 'number-series' },
  { num: [2, 4, 8, 16], next: '32', desc: 'Multiply by 2 each time', category: 'number-series' },
  { num: [1, 3, 9, 27], next: '81', desc: 'Multiply by 3 each time', category: 'number-series' },
  { num: [5, 10, 20, 40], next: '80', desc: 'Multiply by 2', category: 'number-series' },
  { num: [64, 32, 16, 8], next: '4', desc: 'Divide by 2 each time', category: 'number-series' },
  { num: [81, 27, 9, 3], next: '1', desc: 'Divide by 3 each time', category: 'number-series' },
  { num: [1, 1, 2, 3, 5], next: '8', desc: 'Fibonacci sequence', category: 'number-series' },
  { num: [0, 1, 1, 2, 3, 5], next: '8', desc: 'Fibonacci from 0', category: 'number-series' },
  { num: [2, 2, 4, 6, 10], next: '16', desc: 'Modified Fibonacci', category: 'number-series' },
  { num: [1, 4, 7, 10, 13], next: '16', desc: 'Add 3 each time', category: 'number-series' },
  { num: [2, 6, 18, 54], next: '162', desc: 'Multiply by 3', category: 'number-series' },
  { num: [1, 2, 4, 7, 11], next: '16', desc: 'Add 1,2,3,4,5...', category: 'number-series' },
  { num: [3, 3, 6, 9, 15], next: '24', desc: 'Sum of previous two', category: 'number-series' },
  { num: [5, 8, 11, 14, 17], next: '20', desc: 'Add 3', category: 'number-series' },
  { num: [10, 11, 13, 16, 20], next: '25', desc: 'Add incrementing', category: 'number-series' },
  { num: [1, 2, 3, 5, 8, 13], next: '21', desc: 'Fibonacci continued', category: 'number-series' },
  { num: [4, 8, 12, 16, 20], next: '24', desc: 'Add 4', category: 'number-series' },
  { num: [6, 12, 18, 24, 30], next: '36', desc: 'Add 6', category: 'number-series' },
  { num: [9, 18, 27, 36, 45], next: '54', desc: 'Add 9', category: 'number-series' },
  { num: [15, 30, 45, 60, 75], next: '90', desc: 'Add 15', category: 'number-series' },
  { num: [0, 1, 4, 9, 16], next: '25', desc: 'Perfect squares', category: 'number-series' },
  { num: [1, 8, 27, 64, 125], next: '216', desc: 'Perfect cubes', category: 'number-series' },
  { num: [2, 3, 5, 7, 11], next: '13', desc: 'Prime numbers', category: 'number-series' },
  { num: [4, 9, 16, 25, 36], next: '49', desc: 'Squares from 2', category: 'number-series' },
  { num: [1, 3, 6, 10, 15], next: '21', desc: 'Triangular numbers', category: 'number-series' },
  { num: [11, 22, 33, 44, 55], next: '66', desc: 'Multiples of 11', category: 'number-series' },
  { num: [7, 14, 21, 28, 35], next: '42', desc: 'Multiples of 7', category: 'number-series' },
  { num: [13, 26, 39, 52, 65], next: '78', desc: 'Multiples of 13', category: 'number-series' },
  { num: [5, 15, 25, 35, 45], next: '55', desc: 'Add 10', category: 'number-series' },
  { num: [2, 5, 10, 17, 26], next: '37', desc: 'Add 3,5,7,9,11...', category: 'number-series' },
  { num: [20, 19, 17, 14, 10], next: '5', desc: 'Subtract 1,2,3,4,5...', category: 'number-series' },
  { num: [99, 88, 77, 66, 55], next: '44', desc: 'Subtract 11', category: 'number-series' },
  { num: [1, 2, 4, 8, 16], next: '32', desc: 'Powers of 2', category: 'number-series' },
  { num: [1, 3, 9, 27, 81], next: '243', desc: 'Powers of 3', category: 'number-series' },
  { num: [2, 8, 18, 32, 50], next: '72', desc: '2n²', category: 'number-series' },
  { num: [1, 5, 13, 25, 41], next: '61', desc: 'Add 4,8,12,16...', category: 'number-series' },
  { num: [3, 9, 27, 81, 243], next: '729', desc: 'Powers of 3', category: 'number-series' },
  { num: [2, 4, 6, 8, 10], next: '12', desc: 'Even numbers', category: 'number-series' },
  { num: [1, 3, 5, 7, 9], next: '11', desc: 'Odd numbers', category: 'number-series' },
  { num: [2, 5, 8, 11], next: '14', desc: 'Add 3', category: 'number-series' },
  { num: [1, 4, 7, 10], next: '13', desc: 'Add 3', category: 'number-series' },
  { num: [8, 16, 24, 32], next: '40', desc: 'Add 8', category: 'number-series' },
  { num: [19, 38, 57, 76], next: '95', desc: 'Add 19', category: 'number-series' },
  { num: [21, 42, 63, 84], next: '105', desc: 'Add 21', category: 'number-series' },
  { num: [250, 225, 200, 175], next: '150', desc: 'Subtract 25', category: 'number-series' },
  { num: [120, 110, 100, 90], next: '80', desc: 'Subtract 10', category: 'number-series' },
  { num: [55, 50, 45, 40], next: '35', desc: 'Subtract 5', category: 'number-series' },
  { num: [36, 32, 28, 24], next: '20', desc: 'Subtract 4', category: 'number-series' },
  { num: [1, 6, 11, 16], next: '21', desc: 'Add 5', category: 'number-series' },
  { num: [2, 7, 12, 17], next: '22', desc: 'Add 5', category: 'number-series' },
  { num: [3, 8, 13, 18], next: '23', desc: 'Add 5', category: 'number-series' },
  { num: [4, 9, 14, 19], next: '24', desc: 'Add 5', category: 'number-series' },
  { num: [0, 5, 10, 15], next: '20', desc: 'Add 5', category: 'number-series' },
  { num: [22, 20, 18, 16], next: '14', desc: 'Subtract 2', category: 'number-series' },
  { num: [30, 27, 24, 21], next: '18', desc: 'Subtract 3', category: 'number-series' },
  { num: [40, 36, 32, 28], next: '24', desc: 'Subtract 4', category: 'number-series' },
  { num: [50, 44, 38, 32], next: '26', desc: 'Subtract 6', category: 'number-series' },
  { num: [60, 54, 48, 42], next: '36', desc: 'Subtract 6', category: 'number-series' },
  { num: [70, 63, 56, 49], next: '42', desc: 'Subtract 7', category: 'number-series' },
  { num: [80, 72, 64, 56], next: '48', desc: 'Subtract 8', category: 'number-series' },
  { num: [90, 81, 72, 63], next: '54', desc: 'Subtract 9', category: 'number-series' },
  { num: [5, 11, 17, 23], next: '29', desc: 'Add 6', category: 'number-series' },
  { num: [3, 10, 17, 24], next: '31', desc: 'Add 7', category: 'number-series' },
  { num: [1, 9, 17, 25], next: '33', desc: 'Add 8', category: 'number-series' },
  { num: [2, 11, 20, 29], next: '38', desc: 'Add 9', category: 'number-series' },
  { num: [3, 6, 12, 24], next: '48', desc: 'Multiply by 2', category: 'number-series' },
  { num: [4, 12, 36, 108], next: '324', desc: 'Multiply by 3', category: 'number-series' },
  { num: [2, 10, 50, 250], next: '1250', desc: 'Multiply by 5', category: 'number-series' },
  { num: [1, 4, 16, 64], next: '256', desc: 'Multiply by 4', category: 'number-series' },

  // EASY - PATTERNS (60 questions)
  { seq: 'ABAB', next: 'A', desc: 'Simple alternation', category: 'patterns' },
  { seq: 'XYXY', next: 'X', desc: 'Alternating X-Y', category: 'patterns' },
  { seq: 'ABCABC', next: 'A', desc: 'Three-letter repeat', category: 'patterns' },
  { seq: 'XYZXYZ', next: 'X', desc: 'Three-letter repeat', category: 'patterns' },
  { seq: 'AABBAABB', next: 'A', desc: 'Pair repeat', category: 'patterns' },
  { seq: 'AABBCCAABBCC', next: 'A', desc: 'Three-pair repeat', category: 'patterns' },
  { seq: 'ABCDEFABCDEF', next: 'A', desc: 'Six-letter repeat', category: 'patterns' },
  { seq: '121212', next: '1', desc: 'Number alternating', category: 'patterns' },
  { seq: '123123123', next: '1', desc: 'Three-number repeat', category: 'patterns' },
  { seq: '1234512345', next: '1', desc: 'Five-number repeat', category: 'patterns' },
  { seq: 'AABAAB', next: 'A', desc: 'AAB pattern', category: 'patterns' },
  { seq: 'ABBAABBA', next: 'A', desc: 'ABBA pattern', category: 'patterns' },
  { seq: 'AABBAA', next: 'B', desc: 'AA-BB-AA', category: 'patterns' },
  { seq: '112211', next: '2', desc: 'Number pair', category: 'patterns' },
  { seq: '123321', next: '1', desc: 'Palindrome', category: 'patterns' },
  { seq: 'AABBCC', next: 'A', desc: 'Letter pairs', category: 'patterns' },
  { seq: 'AAABBBCCC', next: 'A', desc: 'Triple repeat', category: 'patterns' },
  { seq: 'ABCABCABC', next: 'A', desc: 'Three-letter repeat', category: 'patterns' },
  { seq: 'Red, Blue, Red, Blue', next: 'Red', desc: 'Alternating colours', category: 'patterns' },
  { seq: 'XYXYXY', next: 'X', desc: 'Alternating pairs', category: 'patterns' },
  { seq: '12341234', next: '1', desc: 'Four-number repeat', category: 'patterns' },
  { seq: 'AABBCCDD', next: 'A', desc: 'Pair repeat', category: 'patterns' },
  { seq: 'ABCDEFG', next: 'A', desc: 'Seven-letter cycle', category: 'patterns' },
  { seq: '1357913579', next: '1', desc: 'Odd numbers repeat', category: 'patterns' },
  { seq: 'PQPQPQ', next: 'P', desc: 'Two-letter alternation', category: 'patterns' },
  { seq: 'MNMN', next: 'M', desc: 'Two-letter alternation', category: 'patterns' },
  { seq: 'RSTRST', next: 'R', desc: 'Three-letter repeat', category: 'patterns' },
  { seq: 'UVUVUV', next: 'U', desc: 'Alternating', category: 'patterns' },
  { seq: '101010', next: '1', desc: 'Binary-like', category: 'patterns' },
  { seq: 'WXWXWX', next: 'W', desc: 'Alternating', category: 'patterns' },
  { seq: 'DEFDEF', next: 'D', desc: 'Three-letter repeat', category: 'patterns' },
  { seq: '456456', next: '4', desc: 'Three-number repeat', category: 'patterns' },
  { seq: 'JKLJKL', next: 'J', desc: 'Three-letter repeat', category: 'patterns' },
  { seq: 'PQRPQR', next: 'P', desc: 'Three-letter repeat', category: 'patterns' },
  { seq: 'BCBCBC', next: 'B', desc: 'BC alternation', category: 'patterns' },
  { seq: '242424', next: '2', desc: 'Number alternation', category: 'patterns' },
  { seq: 'RSRSRS', next: 'R', desc: 'Two-letter alternation', category: 'patterns' },
  { seq: '989898', next: '9', desc: 'Number alternation', category: 'patterns' },
  { seq: 'HIHIHI', next: 'H', desc: 'Two-letter alternation', category: 'patterns' },
  { seq: 'KLKLKL', next: 'K', desc: 'Two-letter alternation', category: 'patterns' },
  { seq: '757575', next: '7', desc: 'Number alternation', category: 'patterns' },
  { seq: '303030', next: '3', desc: 'Number pattern', category: 'patterns' },
  { seq: 'CDCDCD', next: 'C', desc: 'Two-letter alternation', category: 'patterns' },
  { seq: '414141', next: '4', desc: 'Number alternation', category: 'patterns' },
  { seq: 'EFEF', next: 'E', desc: 'Two-letter alternation', category: 'patterns' },
  { seq: '565656', next: '5', desc: 'Number alternation', category: 'patterns' },
  { seq: 'GHGH', next: 'G', desc: 'Two-letter alternation', category: 'patterns' },
  { seq: '727272', next: '7', desc: 'Number alternation', category: 'patterns' },
  { seq: 'IJIJ', next: 'I', desc: 'IJ alternation', category: 'patterns' },
  { seq: '636363', next: '6', desc: '63 alternation', category: 'patterns' },
  { seq: 'OPOP', next: 'O', desc: 'OP alternation', category: 'patterns' },
  { seq: '323232', next: '3', desc: '32 alternation', category: 'patterns' },
  { seq: 'QRQR', next: 'Q', desc: 'QR alternation', category: 'patterns' },
  { seq: 'TUVTUVTUV', next: 'T', desc: 'TUV repeat', category: 'patterns' },
  { seq: 'YZYZYZ', next: 'Y', desc: 'YZ alternation', category: 'patterns' },
  { seq: '919191', next: '9', desc: '91 alternation', category: 'patterns' },

  // EASY - PUZZLES (30 questions)
  { q: 'What has keys but no lock?', a: 'Piano', opts: ['Piano', 'Door', 'Safe', 'Box'], category: 'puzzles' },
  { q: 'What gets wetter when drying?', a: 'Towel', opts: ['Towel', 'Sponge', 'Paper', 'Cloth'], category: 'puzzles' },
  { q: 'What has a face but cannot smile?', a: 'Clock', opts: ['Clock', 'Mask', 'Statue', 'Doll'], category: 'puzzles' },
  { q: 'What has hands but cannot clap?', a: 'Clock', opts: ['Clock', 'Robot', 'Statue', 'Doll'], category: 'puzzles' },
  { q: 'What has a neck but no head?', a: 'Bottle', opts: ['Bottle', 'Turtle', 'Giraffe', 'Swan'], category: 'puzzles' },
  { q: 'I have cities but no houses?', a: 'Map', opts: ['Map', 'Country', 'Atlas', 'Globe'], category: 'puzzles' },
  { q: 'What has teeth but cannot bite?', a: 'Comb', opts: ['Comb', 'Saw', 'Fork', 'Rake'], category: 'puzzles' },
  { q: 'What can run but never walks?', a: 'Water', opts: ['Water', 'River', 'Stream', 'Animal'], category: 'puzzles' },
  { q: 'What has branches but no fruit?', a: 'Tree', opts: ['Tree', 'Bush', 'Plant', 'Shrub'], category: 'puzzles' },
  { q: 'I speak without a mouth?', a: 'Echo', opts: ['Echo', 'Wind', 'Sound', 'Silence'], category: 'puzzles' },
  { q: 'What is always coming but never arrives?', a: 'Tomorrow', opts: ['Tomorrow', 'Time', 'Future', 'Night'], category: 'puzzles' },
  { q: 'What has a head and tail but no body?', a: 'Coin', opts: ['Coin', 'Kite', 'Fish', 'Snake'], category: 'puzzles' },
  { q: 'What can you catch but not throw?', a: 'Cold', opts: ['Cold', 'Disease', 'Flu', 'Fever'], category: 'puzzles' },
  { q: 'What becomes smaller upside down?', a: '9', opts: ['9', '8', '7', '6'], category: 'puzzles' },
  { q: 'What has 4 eyes but cannot see?', a: 'Potato', opts: ['Potato', 'Button', 'Corn', 'Coconut'], category: 'puzzles' },
  { q: 'What goes up and never comes down?', a: 'Age', opts: ['Age', 'Time', 'Height', 'Weight'], category: 'puzzles' },
  { q: 'What has a ring but no finger?', a: 'Telephone', opts: ['Telephone', 'Bell', 'Horn', 'Speaker'], category: 'puzzles' },
  { q: 'What has legs but cannot walk?', a: 'Table', opts: ['Table', 'Chair', 'Desk', 'Bed'], category: 'puzzles' },
  { q: 'What has a spine but no bones?', a: 'Book', opts: ['Book', 'Magazine', 'Newspaper', 'Notebook'], category: 'puzzles' },
  { q: 'What goes through cities but never walks?', a: 'River', opts: ['River', 'Road', 'Path', 'Stream'], category: 'puzzles' },
  { q: 'What has a head and a bed but no sleep?', a: 'River', opts: ['River', 'Stream', 'Lake', 'Ocean'], category: 'puzzles' },
  { q: 'What gets shorter as it grows?', a: 'Candle', opts: ['Candle', 'Plant', 'Hair', 'Tree'], category: 'puzzles' },
  { q: 'What has a bottom at the top?', a: 'Mountain', opts: ['Mountain', 'Hill', 'Staircase', 'Ladder'], category: 'puzzles' },
  { q: 'What can travel the world staying in corner?', a: 'Stamp', opts: ['Stamp', 'Letter', 'Envelope', 'Package'], category: 'puzzles' },
  { q: 'What fills a room but takes no space?', a: 'Light', opts: ['Light', 'Air', 'Sound', 'Heat'], category: 'puzzles' },

  // EASY - APTITUDE (25 questions)
  { q: 'If A = 5 and B = 3, what is A + B?', a: '8', opts: ['8', '2', '15', '5'], category: 'aptitude' },
  { q: 'What is 50% of 100?', a: '50', opts: ['50', '25', '75', '100'], category: 'aptitude' },
  { q: 'If x = 4, what is 2x + 3?', a: '11', opts: ['11', '8', '7', '14'], category: 'aptitude' },
  { q: 'A car travels 60 km/h. Distance in 2 hours?', a: '120 km', opts: ['120 km', '60 km', '30 km', '180 km'], category: 'aptitude' },
  { q: 'If 3x = 12, what is x?', a: '4', opts: ['4', '3', '12', '36'], category: 'aptitude' },
  { q: 'What is 10% of 50?', a: '5', opts: ['5', '10', '50', '500'], category: 'aptitude' },
  { q: 'If y = 2, what is y²?', a: '4', opts: ['4', '2', '8', '6'], category: 'aptitude' },
  { q: 'A book costs $10, 5 books cost?', a: '$50', opts: ['$50', '$10', '$15', '$25'], category: 'aptitude' },
  { q: 'If A = 7 and B = 2, what is A - B?', a: '5', opts: ['5', '9', '14', '3.5'], category: 'aptitude' },
  { q: 'What is 25% of 80?', a: '20', opts: ['20', '25', '55', '80'], category: 'aptitude' },
  { q: 'If z = 5, what is 3z?', a: '15', opts: ['15', '5', '8', '25'], category: 'aptitude' },
  { q: 'Man earns $100/day, earns in 7 days?', a: '$700', opts: ['$700', '$100', '$70', '$1000'], category: 'aptitude' },
  { q: 'If 2x = 10, what is x?', a: '5', opts: ['5', '2', '10', '20'], category: 'aptitude' },
  { q: 'What is 33% of 99?', a: '33', opts: ['33', '66', '99', '11'], category: 'aptitude' },
  { q: 'If p = 6 and q = 2, p + q = ?', a: '8', opts: ['8', '4', '12', '3'], category: 'aptitude' },
  { q: 'Train travels 80 km in 2 hours, speed?', a: '40 km/h', opts: ['40 km/h', '80 km/h', '20 km/h', '160 km/h'], category: 'aptitude' },
  { q: 'If m = 9, what is m - 3?', a: '6', opts: ['6', '9', '12', '3'], category: 'aptitude' },
  { q: 'What is 20% of 100?', a: '20', opts: ['20', '80', '50', '120'], category: 'aptitude' },
  { q: 'If n = 4, what is n²?', a: '16', opts: ['16', '8', '4', '2'], category: 'aptitude' },
  { q: 'Shirt costs $15, 3 shirts cost?', a: '$45', opts: ['$45', '$15', '$30', '$60'], category: 'aptitude' },
  { q: 'If d = 10, what is d/2?', a: '5', opts: ['5', '10', '20', '2'], category: 'aptitude' },
  { q: 'What is 15% of 200?', a: '30', opts: ['30', '15', '50', '200'], category: 'aptitude' },
  { q: 'If c = 8, what is 2c?', a: '16', opts: ['16', '8', '4', '10'], category: 'aptitude' },
  { q: 'Speed is 50 km/h for 3 hours?', a: '150 km', opts: ['150 km', '50 km', '100 km', '200 km'], category: 'aptitude' },
  { q: 'What is 5% of 60?', a: '3', opts: ['3', '5', '6', '12'], category: 'aptitude' },

  // EASY - REASONING (25 questions)
  { q: 'All dogs are animals. Buddy is a dog?', a: 'Yes', opts: ['Yes', 'No', 'Maybe', 'Cannot tell'], category: 'reasoning' },
  { q: 'If A > B and B > C, is A > C?', a: 'Yes', opts: ['Yes', 'No', 'Maybe', 'Cannot determine'], category: 'reasoning' },
  { q: 'All fruits have seeds. Apple is fruit?', a: 'Yes', opts: ['Yes', 'No', 'Maybe', 'Cannot tell'], category: 'reasoning' },
  { q: 'If x = 5 and x < 10, what can we say?', a: 'x is less than 10', opts: ['x is less than 10', 'x is greater than 10', 'x equals 10', 'None'], category: 'reasoning' },
  { q: 'No birds are mammals. Penguins are birds?', a: 'No', opts: ['Yes', 'No', 'Maybe', 'Cannot tell'], category: 'reasoning' },
  { q: 'All students study. John is student?', a: 'Yes', opts: ['Yes', 'No', 'Maybe', 'Cannot tell'], category: 'reasoning' },
  { q: 'All flowers are plants. Rose is flower?', a: 'Yes', opts: ['Yes', 'No', 'Maybe', 'Cannot tell'], category: 'reasoning' },
  { q: 'If A = B and B = C, A = C?', a: 'Yes', opts: ['Yes', 'No', 'Maybe', 'Cannot tell'], category: 'reasoning' },
  { q: 'Some apples are red. All red apples sweet?', a: 'Cannot determine', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'All cats have whiskers. Tom is cat?', a: 'Yes', opts: ['Yes', 'No', 'Cannot tell', 'Maybe'], category: 'reasoning' },
  { q: 'If X faster than Y, Y faster than Z?', a: 'X', opts: ['X', 'Y', 'Z', 'Cannot tell'], category: 'reasoning' },
  { q: 'No vegetables are fruits. Carrot is fruit?', a: 'No', opts: ['Yes', 'No', 'Maybe', 'Cannot tell'], category: 'reasoning' },
  { q: 'All houses have doors. Building is house?', a: 'Yes', opts: ['Yes', 'No', 'Maybe', 'Cannot tell'], category: 'reasoning' },
  { q: 'Some people like pizza. John likes pizza?', a: 'Cannot determine', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'If cold, I wear coat. Wearing coat?', a: 'Cannot determine', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'All metals are elements. Iron element?', a: 'Yes', opts: ['Yes', 'No', 'Maybe', 'Cannot tell'], category: 'reasoning' },
  { q: 'No snakes are mammals. Snake mammal?', a: 'No', opts: ['Yes', 'No', 'Maybe', 'Cannot tell'], category: 'reasoning' },
  { q: 'If A north of B, B north of C?', a: 'Yes', opts: ['Yes', 'No', 'Maybe', 'Cannot determine'], category: 'reasoning' },
  { q: 'All doctors are educated. Tom educated?', a: 'Cannot determine', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'Some athletes are smart. All smart rich?', a: 'Cannot determine', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'All teachers help students. Maria helps?', a: 'Cannot determine', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'No reptiles have fur. Snake has fur?', a: 'No', opts: ['Yes', 'No', 'Maybe', 'Cannot tell'], category: 'reasoning' },
  { q: 'All squares are rectangles. Figure rect?', a: 'Cannot determine', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'Some birds fly. All birds fly?', a: 'No', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'If rain then wet. Ground wet?', a: 'Cannot determine', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },

  // EASY - BOOLEAN LOGIC (20 questions)
  { q: 'What is the value of: !true', a: 'false', opts: ['true', 'false', 'undefined', 'null'], category: 'boolean-logic' },
  { q: 'What is (true && false)?', a: 'false', opts: ['true', 'false', '1', '0'], category: 'boolean-logic' },
  { q: 'What is (true || false)?', a: 'true', opts: ['true', 'false', '1', '0'], category: 'boolean-logic' },
  { q: 'Result of: !(false || false)', a: 'true', opts: ['true', 'false', 'error', '0'], category: 'boolean-logic' },
  { q: 'Result of: (true && true) && false', a: 'false', opts: ['true', 'false', 'null', '1'], category: 'boolean-logic' },
  { q: 'If x=true, what is !(!x)?', a: 'true', opts: ['true', 'false', 'undefined', 'x'], category: 'boolean-logic' },
  { q: 'What is (1 == "1") in JS logic?', a: 'true', opts: ['true', 'false', 'error', 'undefined'], category: 'boolean-logic' },
  { q: 'Result of: false && true || true', a: 'true', opts: ['true', 'false', '0', 'undefined'], category: 'boolean-logic' },
  { q: 'What is !!1?', a: 'true', opts: ['true', 'false', '1', '0'], category: 'boolean-logic' },
  { q: 'What is !!0?', a: 'false', opts: ['true', 'false', '1', '0'], category: 'boolean-logic' },

  // EASY - ALGORITHMIC LOGIC (15 questions)
  { q: 'Step 1: X=5. Step 2: X=X+2. What is X?', a: '7', opts: ['5', '7', '10', '2'], category: 'algorithmic-logic' },
  { q: 'Start = 10. Repeat 3 times: subtract 2. Result?', a: '4', opts: ['8', '6', '4', '2'], category: 'algorithmic-logic' },
  { q: 'If Input=3, Step: Result=Input*Input. Result?', a: '9', opts: ['6', '9', '12', '3'], category: 'algorithmic-logic' },
  { q: 'Loop: For i=1 to 3, Sum = Sum + 1. If start Sum=0, final Sum?', a: '3', opts: ['1', '2', '3', '4'], category: 'algorithmic-logic' },
  { q: 'If X > 10 return "High" else "Low". If X is 5?', a: 'Low', opts: ['High', 'Low', '5', 'Error'], category: 'algorithmic-logic' }
];

const mediumQuestions = [
  // MEDIUM - NUMBER SERIES (70 questions)
  { num: [2, 6, 12, 20, 30], next: '42', desc: 'n(n+1) pattern', category: 'number-series' },
  { num: [1, 4, 9, 16, 25], next: '36', desc: 'Perfect squares', category: 'number-series' },
  { num: [3, 6, 12, 24, 48], next: '96', desc: 'Multiply by 2', category: 'number-series' },
  { num: [1, 2, 6, 24, 120], next: '720', desc: 'Factorial sequence', category: 'number-series' },
  { num: [5, 11, 19, 29, 41], next: '55', desc: 'Add 6,8,10,12,14...', category: 'number-series' },
  { num: [1, 2, 4, 7, 11, 16], next: '22', desc: 'Add 1,2,3,4,5,6...', category: 'number-series' },
  { num: [2, 3, 8, 63], next: '3968', desc: 'Each = (prev*prev)-prev', category: 'number-series' },
  { num: [10, 20, 40, 80, 160], next: '320', desc: 'Multiply by 2', category: 'number-series' },
  { num: [1, 4, 10, 20, 35], next: '56', desc: 'Tetrahedral numbers', category: 'number-series' },
  { num: [3, 5, 8, 13, 21], next: '34', desc: 'Modified Fibonacci', category: 'number-series' },
  { num: [2, 5, 11, 23, 47], next: '95', desc: 'Each = prev*2+1', category: 'number-series' },
  { num: [6, 12, 24, 48, 96], next: '192', desc: 'Multiply by 2', category: 'number-series' },
  { num: [1, 5, 14, 30, 55], next: '91', desc: 'Triangular sum', category: 'number-series' },
  { num: [4, 12, 36, 108, 324], next: '972', desc: 'Multiply by 3', category: 'number-series' },
  { num: [7, 14, 28, 56, 112], next: '224', desc: 'Multiply by 2', category: 'number-series' },
  { num: [1, 6, 15, 28, 45], next: '66', desc: 'Pronic n(n+1)', category: 'number-series' },
  { num: [2, 8, 18, 32, 50], next: '72', desc: '2n²', category: 'number-series' },
  { num: [3, 12, 27, 48, 75], next: '108', desc: '3n²', category: 'number-series' },
  { num: [5, 20, 45, 80, 125], next: '180', desc: '5n²', category: 'number-series' },
  { num: [1, 8, 27, 64, 125], next: '216', desc: 'Cubes', category: 'number-series' },
  { num: [2, 6, 18, 54, 162], next: '486', desc: 'Multiply by 3', category: 'number-series' },
  { num: [3, 9, 27, 81, 243], next: '729', desc: 'Powers of 3', category: 'number-series' },
  { num: [4, 16, 64, 256, 1024], next: '4096', desc: 'Powers of 4', category: 'number-series' },
  { num: [1, 4, 16, 64, 256], next: '1024', desc: 'Powers of 4', category: 'number-series' },
  { num: [2, 4, 8, 16, 32], next: '64', desc: 'Powers of 2', category: 'number-series' },
  { num: [3, 12, 48, 192, 768], next: '3072', desc: 'Multiply by 4', category: 'number-series' },
  { num: [1, 9, 25, 49, 81], next: '121', desc: 'Odd squares', category: 'number-series' },
  { num: [4, 16, 36, 64, 100], next: '144', desc: 'Even squares', category: 'number-series' },
  { num: [2, 10, 30, 68, 130], next: '222', desc: 'Diff double each', category: 'number-series' },
  { num: [5, 15, 45, 135, 405], next: '1215', desc: 'Multiply by 3', category: 'number-series' },
  { num: [10, 15, 21, 28, 36], next: '45', desc: 'Triangular +9', category: 'number-series' },
  { num: [2, 7, 26, 101, 400], next: '1597', desc: 'Each = 4*prev-1', category: 'number-series' },
  { num: [1, 3, 7, 15, 31], next: '63', desc: '2^n - 1', category: 'number-series' },
  { num: [10, 11, 13, 17, 25], next: '41', desc: 'Add 1,2,4,8,16...', category: 'number-series' },
  { num: [3, 15, 35, 63, 99], next: '143', desc: '4n²-1', category: 'number-series' },
  { num: [5, 7, 11, 19, 35], next: '67', desc: 'Add 2,4,8,16,32...', category: 'number-series' },
  { num: [1, 1, 2, 3, 5, 8, 13], next: '21', desc: 'Fibonacci', category: 'number-series' },
  { num: [6, 28, 120, 496, 2016], next: '8128', desc: 'Perfect numbers', category: 'number-series' },
  { num: [1, 2, 3, 5, 8, 13, 21], next: '34', desc: 'Fibonacci', category: 'number-series' },
  { num: [2, 3, 5, 8, 13], next: '21', desc: 'Fibonacci-like', category: 'number-series' },
  { num: [3, 3, 6, 9, 15], next: '24', desc: 'Sum prev two', category: 'number-series' },
  { num: [100, 50, 25, 12], next: '6', desc: 'Divide by 2', category: 'number-series' },
  { num: [5, 5, 10, 15, 25], next: '40', desc: 'Fib-like', category: 'number-series' },
  { num: [1, 1, 1, 3, 5, 9], next: '17', desc: 'Complex pattern', category: 'number-series' },
  { num: [2, 3, 5, 7, 11, 13], next: '17', desc: 'Primes', category: 'number-series' },
  { num: [10, 20, 40, 80], next: '160', desc: 'Multiply by 2', category: 'number-series' },
  { num: [5, 10, 15, 20], next: '25', desc: 'Add 5', category: 'number-series' },
  { num: [1, 3, 6, 10, 15, 21], next: '28', desc: 'Triangular', category: 'number-series' },
  { num: [2, 2, 4, 6, 10], next: '16', desc: 'Sum prev 2', category: 'number-series' },
  { num: [1, 3, 5, 7], next: '9', desc: 'Odd numbers', category: 'number-series' },
  { num: [2, 5, 10, 17], next: '26', desc: 'Add squares', category: 'number-series' },
  { num: [1, 2, 4, 8], next: '16', desc: 'Powers of 2', category: 'number-series' },
  { num: [3, 8, 15, 24], next: '35', desc: 'n²-1', category: 'number-series' },
  { num: [4, 9, 16, 25], next: '36', desc: 'Squares', category: 'number-series' },
  { num: [1, 4, 9, 16], next: '25', desc: 'Squares', category: 'number-series' },
  { num: [2, 6, 12, 20], next: '30', desc: 'n(n+1)', category: 'number-series' },
  { num: [5, 15, 35, 77], next: '143', desc: '(2n-1)(2n+1)', category: 'number-series' },
  { num: [1, 6, 20, 50], next: '105', desc: 'Tetrahedral-like', category: 'number-series' },
  { num: [2, 8, 26, 80], next: '242', desc: '3^n - 1', category: 'number-series' },
  { num: [1, 7, 25, 61], next: '121', desc: 'n³+n', category: 'number-series' },
  { num: [3, 7, 15, 31], next: '63', desc: '2^n - 1', category: 'number-series' },
  { num: [4, 5, 7, 11], next: '19', desc: 'Add primes', category: 'number-series' },
  { num: [10, 12, 14, 16], next: '18', desc: 'Add 2', category: 'number-series' },
  { num: [1, 2, 3, 4], next: '5', desc: 'Consecutive', category: 'number-series' },
  { num: [5, 10, 20, 40], next: '80', desc: 'Double', category: 'number-series' },
  { num: [100, 99, 97, 94], next: '90', desc: 'Subtract 1,2,3...', category: 'number-series' },
  { num: [2, 3, 5, 7], next: '11', desc: 'Primes', category: 'number-series' },

  // MEDIUM - PATTERNS (75 questions)
  { seq: 'AABBBAAAA', next: 'A', desc: 'Increasing repetition', category: 'patterns' },
  { seq: 'ABCBCBCBC', next: 'B', desc: 'ABC then BC repeats', category: 'patterns' },
  { seq: 'AABAABAA', next: 'B', desc: 'AAB pattern', category: 'patterns' },
  { seq: '112211221', next: '1', desc: 'Increasing', category: 'patterns' },
  { seq: 'ABACABAD', next: 'A', desc: 'Adding letter', category: 'patterns' },
  { seq: 'XYZYZYZYZ', next: 'Y', desc: 'Initial then repeat', category: 'patterns' },
  { seq: 'ABCBCBCBC', next: 'B', desc: 'ABC then BC cycle', category: 'patterns' },
  { seq: '121212121', next: '2', desc: 'Alternating', category: 'patterns' },
  { seq: 'AAABAAABAA', next: 'A', desc: 'AAB pattern', category: 'patterns' },
  { seq: 'AABBAABBAA', next: 'B', desc: 'AABB pattern', category: 'patterns' },
  { seq: 'ABACADABE', next: 'A', desc: 'Expanding', category: 'patterns' },
  { seq: 'XYXZXYXZXY', next: 'X', desc: 'Alternating double', category: 'patterns' },
  { seq: '123213', next: '2', desc: 'Rotation', category: 'patterns' },
  { seq: 'PQRSTPQRST', next: 'P', desc: 'Five-letter repeat', category: 'patterns' },
  { seq: 'AABCAABCAA', next: 'B', desc: 'AABC pattern', category: 'patterns' },
  { seq: 'ABCDABCD', next: 'A', desc: 'Four-letter repeat', category: 'patterns' },
  { seq: 'XXYYZZ', next: 'X', desc: 'Pair pattern', category: 'patterns' },
  { seq: '131313', next: '1', desc: 'Number alternation', category: 'patterns' },
  { seq: 'AAABBBCCC', next: 'D', desc: 'Triplets then continue', category: 'patterns' },
  { seq: 'DEFGDEFG', next: 'D', desc: 'Four-letter repeat', category: 'patterns' },
  { seq: 'ABCDEFABCDEF', next: 'A', desc: 'Six-letter repeat', category: 'patterns' },
  { seq: 'MNMN', next: 'M', desc: 'MN alternation', category: 'patterns' },
  { seq: 'TUVTUVTUV', next: 'T', desc: 'TUV repeat', category: 'patterns' },
  { seq: '565656', next: '5', desc: '56 alternation', category: 'patterns' },
  { seq: 'WXWXWX', next: 'W', desc: 'WX alternation', category: 'patterns' },
  { seq: '787878', next: '7', desc: '78 alternation', category: 'patterns' },
  { seq: 'YZYZYZ', next: 'Y', desc: 'YZ alternation', category: 'patterns' },
  { seq: '919191', next: '9', desc: '91 alternation', category: 'patterns' },
  { seq: 'BCBC', next: 'B', desc: 'BC alternation', category: 'patterns' },
  { seq: '252525', next: '2', desc: '25 alternation', category: 'patterns' },
  { seq: 'IJIJ', next: 'I', desc: 'IJ alternation', category: 'patterns' },
  { seq: '636363', next: '6', desc: '63 alternation', category: 'patterns' },
  { seq: 'KLKL', next: 'K', desc: 'KL alternation', category: 'patterns' },
  { seq: '848484', next: '8', desc: '84 alternation', category: 'patterns' },
  { seq: 'OPOP', next: 'O', desc: 'OP alternation', category: 'patterns' },
  { seq: '323232', next: '3', desc: '32 alternation', category: 'patterns' },
  { seq: 'QRQR', next: 'Q', desc: 'QR alternation', category: 'patterns' },
  { seq: 'AABB', next: 'A', desc: 'AA-BB', category: 'patterns' },
  { seq: '1122', next: '1', desc: '11-22', category: 'patterns' },
  { seq: 'ABAB', next: 'A', desc: 'AB repeat', category: 'patterns' },
  { seq: '1212', next: '1', desc: '12 repeat', category: 'patterns' },
  { seq: 'XYZXYZ', next: 'X', desc: 'XYZ repeat', category: 'patterns' },
  { seq: '123123', next: '1', desc: '123 repeat', category: 'patterns' },
  { seq: 'PQPQ', next: 'P', desc: 'PQ repeat', category: 'patterns' },
  { seq: '3434', next: '3', desc: '34 repeat', category: 'patterns' },
  { seq: 'STST', next: 'S', desc: 'ST repeat', category: 'patterns' },
  { seq: '5656', next: '5', desc: '56 repeat', category: 'patterns' },
  { seq: 'UVUV', next: 'U', desc: 'UV repeat', category: 'patterns' },
  { seq: '7878', next: '7', desc: '78 repeat', category: 'patterns' },
  { seq: 'EFEF', next: 'E', desc: 'EF repeat', category: 'patterns' },
  { seq: '9090', next: '9', desc: '90 repeat', category: 'patterns' },
  { seq: 'AABBAABBAA', next: 'B', desc: 'AABB cycle', category: 'patterns' },
  { seq: 'ABCDABCDAB', next: 'C', desc: 'ABCD repeat', category: 'patterns' },
  { seq: 'MNOPMNOP', next: 'M', desc: 'MNOP pattern', category: 'patterns' },
  { seq: 'ABABAB', next: 'A', desc: 'AB cycle', category: 'patterns' },
  { seq: '654654', next: '6', desc: '654 repeat', category: 'patterns' },
  { seq: 'GHIGHI', next: 'G', desc: 'GHI repeat', category: 'patterns' },
  { seq: '987987', next: '9', desc: '987 repeat', category: 'patterns' },
  { seq: 'JKLJKL', next: 'J', desc: 'JKL repeat', category: 'patterns' },
  { seq: '123456', next: '1', desc: '123456 cycle', category: 'patterns' },
  { seq: 'XYZABC', next: 'X', desc: 'XYZ-ABC repeat', category: 'patterns' },
  { seq: 'AABBCCDD', next: 'A', desc: 'Pairs', category: 'patterns' },
  { seq: '12341234', next: '1', desc: '1234 repeat', category: 'patterns' },
  { seq: 'ABCDEFG', next: 'A', desc: 'Seven cycle', category: 'patterns' },
  { seq: 'XYXYXYXY', next: 'X', desc: 'XY repeat', category: 'patterns' },
  { seq: '11223344', next: '1', desc: '11-22-33-44', category: 'patterns' },
  { seq: 'AABBCCAA', next: 'B', desc: 'Six pattern', category: 'patterns' },
  { seq: '123123123', next: '1', desc: '123 triple', category: 'patterns' },
  { seq: 'ABCABC', next: 'A', desc: 'Three repeat', category: 'patterns' },
  { seq: '454545', next: '4', desc: '45 repeat', category: 'patterns' },
  { seq: 'LMNLMN', next: 'L', desc: 'LMN repeat', category: 'patterns' },

  // MEDIUM - PUZZLES (30 questions)
  { q: 'I am always coming but never arrive?', a: 'Tomorrow', opts: ['Tomorrow', 'Time', 'Future', 'Night'], category: 'puzzles' },
  { q: 'The more you take, more left behind?', a: 'Footsteps', opts: ['Footsteps', 'Time', 'Words', 'Memories'], category: 'puzzles' },
  { q: 'What word becomes shorter adding letters?', a: 'Short', opts: ['Short', 'Long', 'Add', 'Word'], category: 'puzzles' },
  { q: 'What can be given but never taken?', a: 'Advice', opts: ['Advice', 'Gift', 'Money', 'Help'], category: 'puzzles' },
  { q: 'I am everywhere and nowhere?', a: 'Space', opts: ['Space', 'Air', 'Light', 'Time'], category: 'puzzles' },
  { q: 'Cannot be held more than seconds?', a: 'Breath', opts: ['Breath', 'Water', 'Fire', 'Ice'], category: 'puzzles' },
  { q: 'Starts with E, ends E, one letter?', a: 'Envelope', opts: ['Envelope', 'Example', 'Escape', 'Explore'], category: 'puzzles' },
  { q: 'Light as feather, strongest man?', a: 'Breath', opts: ['Breath', 'Air', 'Wind', 'Smoke'], category: 'puzzles' },
  { q: 'Once in minute, twice moment, never hundred?', a: 'M', opts: ['M', 'O', 'E', 'T'], category: 'puzzles' },
  { q: 'I am three eyes and one foot?', a: 'Traffic light', opts: ['Traffic light', 'One-legged', 'Bird', 'Ostrich'], category: 'puzzles' },
  { q: 'Difference between here and there?', a: 'The letter T', opts: ['The letter T', 'Distance', 'Location', 'Direction'], category: 'puzzles' },
  { q: 'Black getting, red using, white done?', a: 'Charcoal', opts: ['Charcoal', 'Fire', 'Coal', 'Ash'], category: 'puzzles' },
  { q: 'Can honk without using horn?', a: 'Goose', opts: ['Goose', 'Duck', 'Bird', 'Swan'], category: 'puzzles' },
  { q: 'What is better than gold?', a: 'Friendship', opts: ['Friendship', 'Love', 'Family', 'Health'], category: 'puzzles' },
  { q: 'What is at end of road?', a: 'D', opts: ['D', 'O', 'A', 'E'], category: 'puzzles' },
  { q: 'Building has most stories?', a: 'Library', opts: ['Library', 'Skyscraper', 'Hotel', 'Apartment'], category: 'puzzles' },
  { q: 'Stays on ground never gets dirty?', a: 'Shadow', opts: ['Shadow', 'Grass', 'Dirt', 'Mud'], category: 'puzzles' },
  { q: 'Follow everywhere cannot see it?', a: 'Footsteps', opts: ['Footsteps', 'Shadow', 'Echo', 'Memory'], category: 'puzzles' },
  { q: 'Five-letter word shorter add letters?', a: 'Short', opts: ['Short', 'Thick', 'Large', 'Small'], category: 'puzzles' },
  { q: 'Smallest unit of life?', a: 'Cell', opts: ['Cell', 'Atom', 'Gene', 'Molecule'], category: 'puzzles' },
  { q: 'Becomes more wet while drying?', a: 'Towel', opts: ['Towel', 'Cloth', 'Paper', 'Sponge'], category: 'puzzles' },
  { q: 'Always in front cannot be seen?', a: 'Future', opts: ['Future', 'Time', 'Tomorrow', 'Night'], category: 'puzzles' },
  { q: 'I am odd number. Take away letter?', a: 'Seven', opts: ['Seven', 'Three', 'Five', 'Nine'], category: 'puzzles' },
  { q: 'Black morning, red day, yellow night?', a: 'Sky', opts: ['Sky', 'Sun', 'Cloud', 'Light'], category: 'puzzles' },
  { q: 'What bank never holds money?', a: 'River bank', opts: ['River bank', 'Dirt bank', 'Sand bank', 'Grass bank'], category: 'puzzles' },
  { q: 'What has a mouth but never speaks?', a: 'River', opts: ['River', 'Fish', 'Well', 'Stream'], category: 'puzzles' },
  { q: 'I am always in front of you but you cannot see me?', a: 'Future', opts: ['Future', 'Time', 'Space', 'Light'], category: 'puzzles' },
  { q: 'What breaks but never falls?', a: 'Promise', opts: ['Promise', 'Glass', 'Heart', 'Trust'], category: 'puzzles' },
  { q: 'Runs but never walks?', a: 'Water', opts: ['Water', 'River', 'Time', 'Electricity'], category: 'puzzles' },
  { q: 'What question cannot be answered?', a: 'Are you asleep?', opts: ['Are you asleep?', 'Who am I?', 'What time?', 'Where are you?'], category: 'puzzles' },

  // MEDIUM - APTITUDE (25 questions)
  { q: 'If 3x + 5 = 20, what is x?', a: '5', opts: ['5', '3', '10', '25'], category: 'aptitude' },
  { q: 'Train travels 60 km/h. Distance 180 km?', a: '3 hours', opts: ['3 hours', '2 hours', '4 hours', '5 hours'], category: 'aptitude' },
  { q: 'If x:y = 2:3 and y = 9, what is x?', a: '6', opts: ['6', '9', '12', '3'], category: 'aptitude' },
  { q: 'Percentage increase from 50 to 75?', a: '50%', opts: ['50%', '25%', '75%', '33%'], category: 'aptitude' },
  { q: 'If 2x - 3 = 7, what is x?', a: '5', opts: ['5', '3', '7', '10'], category: 'aptitude' },
  { q: 'Discount 20% on $100 leaves?', a: '$80', opts: ['$80', '$20', '$120', '$50'], category: 'aptitude' },
  { q: 'If a:b = 3:4 and a = 6, what is b?', a: '8', opts: ['8', '6', '12', '4'], category: 'aptitude' },
  { q: 'Simple interest $1000 at 5% for 2 years?', a: '$100', opts: ['$100', '$50', '$200', '$500'], category: 'aptitude' },
  { q: 'If 4x = 2x + 10, what is x?', a: '5', opts: ['5', '2', '10', '20'], category: 'aptitude' },
  { q: 'Shirt $50, 30% discount, new price?', a: '$35', opts: ['$35', '$50', '$20', '$80'], category: 'aptitude' },
  { q: 'If x + 2y = 10 and y = 2, x?', a: '6', opts: ['6', '2', '10', '14'], category: 'aptitude' },
  { q: 'What is 15% of 200?', a: '30', opts: ['30', '15', '50', '200'], category: 'aptitude' },
  { q: 'If a:b:c = 2:3:4 and a = 4, c?', a: '8', opts: ['8', '4', '6', '12'], category: 'aptitude' },
  { q: 'Buys 5 pens $2 each, 3 books $5 each total?', a: '$25', opts: ['$25', '$15', '$30', '$35'], category: 'aptitude' },
  { q: 'If 3(x + 2) = 15, what is x?', a: '3', opts: ['3', '2', '5', '15'], category: 'aptitude' },
  { q: 'Percentage of 24 out of 80?', a: '30%', opts: ['30%', '24%', '50%', '75%'], category: 'aptitude' },
  { q: 'If 2x + 3y = 13 and x = 2, y?', a: '3', opts: ['3', '2', '5', '7'], category: 'aptitude' },
  { q: 'Student scores 75% on 80 marks?', a: '60', opts: ['60', '75', '80', '45'], category: 'aptitude' },
  { q: 'If x:5 = 4:10, what is x?', a: '2', opts: ['2', '4', '5', '10'], category: 'aptitude' },
  { q: 'Man travels 30km car, 20km train total?', a: '1.5 hours', opts: ['1.5 hours', '1 hour', '2 hours', '2.5 hours'], category: 'aptitude' },
  { q: 'If a + b = 12 and a = 5, b?', a: '7', opts: ['7', '5', '12', '17'], category: 'aptitude' },
  { q: 'What is 40% of 150?', a: '60', opts: ['60', '40', '150', '75'], category: 'aptitude' },
  { q: 'If 5p = 25, what is p?', a: '5', opts: ['5', '25', '20', '10'], category: 'aptitude' },
  { q: 'Cost $12, profit $3, profit %?', a: '25%', opts: ['25%', '20%', '30%', '15%'], category: 'aptitude' },
  { q: 'Speed 80 km/h for 2.5 hours?', a: '200 km', opts: ['200 km', '80 km', '160 km', '220 km'], category: 'aptitude' },

  // MEDIUM - REASONING (25 questions)
  { q: 'Some cats are black. All black dark?', a: 'Yes', opts: ['Yes', 'No', 'Maybe', 'Cannot determine'], category: 'reasoning' },
  { q: 'All philosophers wise. Some wise rich?', a: 'No', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'If all A are B, all B are C then all A are C?', a: 'Yes', opts: ['Yes', 'No', 'Maybe', 'Cannot determine'], category: 'reasoning' },
  { q: 'No honest are thieves. Ram honest then Ram thief?', a: 'No', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'Some students athletes. Some athletes?', a: 'Cannot determine', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'All engineers problem solvers then all solvers engineers?', a: 'No', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'If A implies B, B false then A?', a: 'A must be false', opts: ['A must be true', 'A must be false', 'A is uncertain', 'Cannot determine'], category: 'reasoning' },
  { q: 'All roses are flowers. All roses red?', a: 'No', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'Every doctor educated. Some educated poor?', a: 'Cannot determine', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'Nobody is perfect. John perfect?', a: 'No', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'All programmers logical. Tom logical?', a: 'Cannot determine', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'Some birds can fly. All flying have wings?', a: 'Cannot determine', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'If A > B and C < B then A > C?', a: 'Yes', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'All fruits grow on trees. Bananas grow on trees?', a: 'Cannot determine', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'No lazy person succeeds. Successful not lazy?', a: 'Yes', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'Some authors poets. All poets creative?', a: 'Cannot determine', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'Study hard implies pass. John passed?', a: 'Cannot determine', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'All mammals have fur. Whale mammal?', a: 'Yes', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'No reptiles warm-blooded. Lizard cold-blooded?', a: 'Yes', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'Some athletes injured. All injured rest?', a: 'Yes', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'If X necessary for Y, Y happens then X?', a: 'Cannot determine', opts: ['X must happen', 'X might happen', 'Cannot determine', 'X must not'], category: 'reasoning' },
  { q: 'All teachers work. Some teachers happy?', a: 'Cannot determine', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'No fool is wise. Foolish not wise?', a: 'Yes', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'If morning then breakfast. Breakfast cooked?', a: 'Cannot determine', opts: ['Must be morning', 'Might be morning', 'Cannot determine', 'Not morning'], category: 'reasoning' },
  { q: 'Some rich are happy. All rich happy?', a: 'No', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },

  // MEDIUM - BOOLEAN LOGIC
  { q: 'Value of: (true && false) || (true && true)', a: 'true', opts: ['true', 'false', 'null', 'undefined'], category: 'boolean-logic' },
  { q: 'Result of: !( (true || false) && (false && true) )', a: 'true', opts: ['true', 'false', 'null', '0'], category: 'boolean-logic' },
  { q: 'If A=true, B=false, what is A && !B?', a: 'true', opts: ['true', 'false', 'A', 'B'], category: 'boolean-logic' },
  { q: 'What is (null || "Hello") in logical evaluation?', a: 'Hello', opts: ['null', 'Hello', 'true', 'false'], category: 'boolean-logic' },
  { q: 'Value of: (5 > 3) && (2 < 1)', a: 'false', opts: ['true', 'false', '5', '1'], category: 'boolean-logic' },

  // MEDIUM - ALGORITHMIC LOGIC
  { q: 'X=10, Y=2. While X > 5: X = X-Y. Final X?', a: '4', opts: ['4', '6', '5', '2'], category: 'algorithmic-logic' },
  { q: 'If Input=4, Result=1. For i=1 to Input: Result=Result*i. Final Result?', a: '24', opts: ['24', '16', '12', '4'], category: 'algorithmic-logic' },
  { q: 'A=5, B=10. Temp=A, A=B, B=Temp. What is B?', a: '5', opts: ['5', '10', '15', '0'], category: 'algorithmic-logic' },

  // DECEPTIVE LOGIC (Lateral Thinking)
  { q: 'How many months have 28 days?', a: 'All 12', opts: ['Only 1', 'All 12', 'The leap ones', '6'], category: 'puzzles' },
  { q: 'If you take 2 apples from 3, how many do you have?', a: '2', opts: ['1', '2', '3', '0'], category: 'puzzles' },
  { q: 'A man builds a house with 4 sides of southern exposure. A bear walks by. Color?', a: 'White', opts: ['Black', 'Brown', 'White', 'Blue'], category: 'puzzles' },
  { q: 'If you are in a race and you pass the person in second place, what place are you in?', a: '2nd', opts: ['1st', '2nd', '3rd', 'Last'], category: 'puzzles' },
  { q: 'What belongs to you but others use it more?', a: 'Your Name', opts: ['Money', 'Phone', 'Your Name', 'Car'], category: 'puzzles' },
  { q: 'A farmer has 17 sheep. All but 9 die. How many are left?', a: '9', opts: ['8', '17', '9', '0'], category: 'puzzles' }
];

const hardQuestions = [
  // HARD - NUMBER SERIES (40 questions)
  { num: [1, 2, 6, 24, 120], next: '720', desc: 'Factorials (n!)', category: 'number-series' },
  { num: [2, 3, 5, 7, 11], next: '13', desc: 'Prime numbers', category: 'number-series' },
  { num: [1, 3, 6, 10, 15], next: '21', desc: 'Triangular numbers', category: 'number-series' },
  { num: [2, 8, 18, 32, 50], next: '72', desc: '2n² pattern', category: 'number-series' },
  { num: [1, 4, 10, 20, 35], next: '56', desc: 'Tetrahedral numbers', category: 'number-series' },
  { num: [5, 11, 19, 29, 41], next: '55', desc: 'Add 6,8,10,12...', category: 'number-series' },
  { num: [1, 2, 4, 7, 11, 16], next: '22', desc: 'Cumulative sum', category: 'number-series' },
  { num: [2, 3, 8, 63, 3968], next: '15745023', desc: 'Each = prev² - prev', category: 'number-series' },
  { num: [1, 1, 2, 3, 5, 8, 13], next: '21', desc: 'Fibonacci', category: 'number-series' },
  { num: [1, 4, 27, 256, 3125], next: '46656', desc: 'Powers n^n', category: 'number-series' },
  { num: [2, 10, 30, 68, 130], next: '222', desc: 'Differences double', category: 'number-series' },
  { num: [1, 8, 27, 64, 125], next: '216', desc: 'Cubes (1³, 2³...)', category: 'number-series' },
  { num: [3, 12, 39, 120, 363], next: '1092', desc: 'Each = 3*prev+prev', category: 'number-series' },
  { num: [1, 5, 14, 30, 55], next: '91', desc: 'Pentagonal numbers', category: 'number-series' },
  { num: [2, 6, 18, 54, 162], next: '486', desc: 'Each = prev * 3', category: 'number-series' },
  { num: [1, 2, 4, 8, 16], next: '32', desc: 'Powers of 2', category: 'number-series' },
  { num: [1, 3, 9, 27, 81], next: '243', desc: 'Powers of 3', category: 'number-series' },
  { num: [1, 4, 9, 16, 25], next: '36', desc: 'Perfect squares', category: 'number-series' },
  { num: [2, 5, 13, 35, 97], next: '275', desc: 'Each = 3*prev - 1', category: 'number-series' },
  { num: [1, 3, 7, 15, 31], next: '63', desc: '2^n - 1', category: 'number-series' },
  { num: [3, 5, 7, 11, 13], next: '17', desc: 'Odd primes', category: 'number-series' },
  { num: [4, 6, 10, 14, 22], next: '26', desc: 'Even composite', category: 'number-series' },
  { num: [5, 15, 35, 75, 155], next: '315', desc: 'Add 10,20,40,80...', category: 'number-series' },
  { num: [1, 6, 15, 28, 45], next: '66', desc: 'Pronic n(n+1)', category: 'number-series' },
  { num: [2, 4, 6, 10, 14], next: '22', desc: 'Sum divisors', category: 'number-series' },
  { num: [1, 4, 10, 20, 35], next: '56', desc: 'Sum triangular', category: 'number-series' },
  { num: [3, 6, 12, 24, 48], next: '96', desc: 'Multiply by 2', category: 'number-series' },
  { num: [1, 2, 4, 7, 14], next: '28', desc: 'Divisor pattern', category: 'number-series' },
  { num: [5, 10, 20, 40, 80], next: '160', desc: 'Multiply by 2', category: 'number-series' },
  { num: [1, 3, 6, 10, 15, 21], next: '28', desc: 'Triangular numbers', category: 'number-series' },
  { num: [2, 7, 26, 101, 400], next: '1597', desc: 'Each = 4*prev - 1', category: 'number-series' },
  { num: [10, 11, 13, 17, 25], next: '41', desc: 'Add 1,2,4,8,16...', category: 'number-series' },
  { num: [3, 9, 27, 81, 243], next: '729', desc: 'Powers of 3', category: 'number-series' },
  { num: [4, 16, 64, 256, 1024], next: '4096', desc: 'Powers of 4', category: 'number-series' },
  { num: [1, 9, 25, 49, 81], next: '121', desc: 'Odd squares', category: 'number-series' },
  { num: [3, 15, 35, 63, 99], next: '143', desc: '4n² - 1', category: 'number-series' },
  { num: [5, 20, 45, 80, 125], next: '180', desc: '5n²', category: 'number-series' },
  { num: [1, 3, 7, 15, 31, 63], next: '127', desc: '2^n - 1', category: 'number-series' },
  { num: [2, 3, 5, 8, 13, 21], next: '34', desc: 'Fibonacci', category: 'number-series' },
  { num: [6, 28, 120, 496, 2016], next: '8128', desc: 'Perfect numbers', category: 'number-series' },

  // HARD - PATTERNS (30 questions)
  { seq: 'AABBAABBAABB', next: 'A', desc: 'Complex AABB cycle', category: 'patterns' },
  { seq: 'ABCABCABCABC', next: 'A', desc: 'ABC 4x repeat', category: 'patterns' },
  { seq: 'AABBCCAABBCC', next: 'A', desc: 'AABBCC repeat', category: 'patterns' },
  { seq: '112233112233', next: '1', desc: 'Pair repeat', category: 'patterns' },
  { seq: 'ABACADAEABAC', next: 'A', desc: 'Complex pattern', category: 'patterns' },
  { seq: 'XYZABCXYZABC', next: 'X', desc: 'Double-triple repeat', category: 'patterns' },
  { seq: 'AAABBBCCCAAA', next: 'A', desc: 'Triple-triple', category: 'patterns' },
  { seq: '123456123456', next: '1', desc: 'Six-digit cycle', category: 'patterns' },
  { seq: 'ABCDABCDABCD', next: 'A', desc: '4-letter 3x', category: 'patterns' },
  { seq: 'PQRSTPQRSTPQ', next: 'R', desc: '5-letter + partial', category: 'patterns' },
  { seq: '121314121314', next: '1', desc: 'Numeric compound', category: 'patterns' },
  { seq: 'XYXYXYXYXYXY', next: 'X', desc: 'XY 6x repeat', category: 'patterns' },
  { seq: 'AABBAA', next: 'B', desc: 'Mirror-like', category: 'patterns' },
  { seq: '454545454545', next: '4', desc: 'Numeric alternate', category: 'patterns' },
  { seq: 'MNOPMNOPMNOP', next: 'M', desc: '4-letter 3x', category: 'patterns' },
  { seq: 'EFGHIJEFGHIJ', next: 'E', desc: '6-letter 2x', category: 'patterns' },
  { seq: '111222111222', next: '1', desc: 'Triple alternate', category: 'patterns' },
  { seq: 'ABCDEFABCDEF', next: 'A', desc: '6-letter 2x', category: 'patterns' },
  { seq: 'STUVWXSTUVWX', next: 'S', desc: '6-letter repeat', category: 'patterns' },
  { seq: '123123123123', next: '1', desc: '3-digit 4x', category: 'patterns' },
  { seq: 'JKLMNOJKLMNO', next: 'J', desc: '6-letter 2x', category: 'patterns' },
  { seq: 'GHIJGHIJGHIJ', next: 'G', desc: '4-letter 3x', category: 'patterns' },
  { seq: '654321654321', next: '6', desc: '6-digit 2x', category: 'patterns' },
  { seq: 'AABBCCDDAABB', next: 'C', desc: 'Pair chain', category: 'patterns' },
  { seq: 'XYZXYZXYZXYZ', next: 'X', desc: '3-letter 4x', category: 'patterns' },
  { seq: '123312312312', next: '3', desc: 'Mixed pattern', category: 'patterns' },
  { seq: 'ABCDEFGABCDE', next: 'F', desc: '7-letter partial', category: 'patterns' },
  { seq: 'PQPQPQPQPQPQ', next: 'P', desc: 'PQ 6x', category: 'patterns' },
  { seq: '789789789789', next: '7', desc: '3-digit 4x', category: 'patterns' },
  { seq: 'KLMKLMKLMKLM', next: 'K', desc: '3-letter 4x', category: 'patterns' },

  // HARD - PUZZLES (30 questions)
  { q: 'What is at the end of everything?', a: 'G', opts: ['G', 'E', 'T', 'H'], category: 'puzzles' },
  { q: 'What has a city but no houses, forest but no trees?', a: 'Map', opts: ['Map', 'Picture', 'Painting', 'Model'], category: 'puzzles' },
  { q: 'I disappear when you say my name. What am I?', a: 'Silence', opts: ['Silence', 'Echo', 'Sound', 'Whisper'], category: 'puzzles' },
  { q: 'What word has letters that appear only once?', a: 'Dialogue', opts: ['Dialogue', 'Unique', 'Mystery', 'Secret'], category: 'puzzles' },
  { q: 'I have keys but no locks. What am I?', a: 'Piano', opts: ['Piano', 'Map', 'Keyboard', 'Door'], category: 'puzzles' },
  { q: 'The more you take, the more you leave behind?', a: 'Footsteps', opts: ['Footsteps', 'Time', 'Memory', 'Shadow'], category: 'puzzles' },
  { q: 'What breaks and never falls, falls but never breaks?', a: 'Night & Day', opts: ['Night & Day', 'Water', 'Stone', 'Light'], category: 'puzzles' },
  { q: 'What has a beginning and end but no body?', a: 'Graveyard', opts: ['Graveyard', 'Bridge', 'Grave', 'Road'], category: 'puzzles' },
  { q: 'What is so fragile that saying its name breaks it?', a: 'Silence', opts: ['Silence', 'Glass', 'Peace', 'Moment'], category: 'puzzles' },
  { q: 'What question can you never answer yes to?', a: 'Are you asleep?', opts: ['Are you asleep?', 'Are you alive?', 'Do you exist?', 'Can you speak?'], category: 'puzzles' },
  { q: 'What word contains all vowels in order?', a: 'Abstemious', opts: ['Abstemious', 'Beautiful', 'Facetious', 'Education'], category: 'puzzles' },
  { q: 'What walks with head and legs but cannot walk?', a: 'Compass', opts: ['Compass', 'Snail', 'Turtle', 'Measuring tape'], category: 'puzzles' },
  { q: 'I am full of keys but cannot open any lock?', a: 'Piano', opts: ['Piano', 'Computer', 'Keyboard', 'Lock'], category: 'puzzles' },
  { q: 'What is always before you but cannot be seen?', a: 'Future', opts: ['Future', 'Light', 'Time', 'Death'], category: 'puzzles' },
  { q: 'What has a bottom at the top?', a: 'Mountain', opts: ['Mountain', 'Bottle', 'Well', 'Pit'], category: 'puzzles' },
  { q: 'I have no body but I come alive with wind?', a: 'Flag', opts: ['Flag', 'Kite', 'Paper', 'Cloth'], category: 'puzzles' },
  { q: 'What is never eaten before it is dried?', a: 'Fruit', opts: ['Fruit', 'Bread', 'Pasta', 'Meat'], category: 'puzzles' },
  { q: 'Becomes new when you use it, old when you dont?', a: 'Skills', opts: ['Skills', 'Tools', 'Clothes', 'Habits'], category: 'puzzles' },
  { q: 'What cannot be held but has weight?', a: 'Debt', opts: ['Debt', 'Burden', 'Worry', 'Responsibility'], category: 'puzzles' },
  { q: 'I have cities but no houses, forests but no trees?', a: 'Map', opts: ['Map', 'Model', 'Game', 'Drawing'], category: 'puzzles' },
  { q: 'What word becomes shorter with a letter added?', a: 'Short', opts: ['Short', 'Word', 'Long', 'Add'], category: 'puzzles' },
  { q: 'What kind of fish chases mice?', a: 'Catfish', opts: ['Catfish', 'Dogfish', 'Ratfish', 'Mousefish'], category: 'puzzles' },
  { q: 'What can flow but has no mouth?', a: 'River', opts: ['River', 'Water', 'Stream', 'Creek'], category: 'puzzles' },
  { q: 'I am taken before you receive me. What am I?', a: 'Picture', opts: ['Picture', 'Photo', 'Shot', 'Image'], category: 'puzzles' },
  { q: 'What is the only mammal that cannot jump?', a: 'Elephant', opts: ['Elephant', 'Whale', 'Hippo', 'Sloth'], category: 'puzzles' },
  { q: 'What has a face but cannot express emotions?', a: 'Clock', opts: ['Clock', 'Mask', 'Statue', 'Doll'], category: 'puzzles' },
  { q: 'The more you share, the less you have. What am I?', a: 'Secret', opts: ['Secret', 'Money', 'Food', 'Time'], category: 'puzzles' },
  { q: 'What has hands but cannot wash itself?', a: 'Clock', opts: ['Clock', 'Robot', 'Statue', 'Skeleton'], category: 'puzzles' },
  { q: 'What gets better with use but worse with neglect?', a: 'Skill', opts: ['Skill', 'Tool', 'Ability', 'Talent'], category: 'puzzles' },
  { q: 'What is at the end of a rainbow?', a: 'W', opts: ['W', 'O', 'E', 'D'], category: 'puzzles' },

  // HARD - APTITUDE (25 questions)
  { q: 'If 5x + 10 = 35, what is 2x?', a: '10', opts: ['10', '5', '15', '20'], category: 'aptitude' },
  { q: 'Compound interest $1000 at 5% for 2 years?', a: '$1102.50', opts: ['$1102.50', '$1100', '$1050', '$1150'], category: 'aptitude' },
  { q: 'If a:b:c = 2:3:5 and a+b+c = 50, find c?', a: '25', opts: ['25', '10', '15', '20'], category: 'aptitude' },
  { q: 'A works 8hrs/day, B 10hrs/day. Work ratio?', a: '4:5', opts: ['4:5', '5:4', '8:10', '2:2.5'], category: 'aptitude' },
  { q: 'If x² - 5x + 6 = 0, what is x?', a: '2 or 3', opts: ['2 or 3', '1 or 6', '2 or 4', '3 or 4'], category: 'aptitude' },
  { q: 'Speed increased 25%, new speed vs original?', a: '1.25x', opts: ['1.25x', '2x', '1.5x', '0.75x'], category: 'aptitude' },
  { q: 'If 3x + 4y = 20 and x = 2, find y?', a: '3.5', opts: ['3.5', '4', '3', '2'], category: 'aptitude' },
  { q: 'Profit 20% on $500, selling price?', a: '$600', opts: ['$600', '$500', '$400', '$700'], category: 'aptitude' },
  { q: 'Distance = Speed × Time, Time = ?', a: 'Distance/Speed', opts: ['Distance/Speed', 'Speed/Distance', 'Speed×Distance', 'Distance-Speed'], category: 'aptitude' },
  { q: 'If log 100 = 2, what is log base?', a: '10', opts: ['10', '2', '100', 'e'], category: 'aptitude' },
  { q: 'Area of circle with radius 7 is?', a: '154', opts: ['154', '49', '98', '77'], category: 'aptitude' },
  { q: 'A loses 10%, then gains 10%. Net?', a: 'Loss 1%', opts: ['Loss 1%', 'No change', 'Gain 1%', 'Loss 2%'], category: 'aptitude' },
  { q: 'If 2^x = 64, what is x?', a: '6', opts: ['6', '3', '8', '4'], category: 'aptitude' },
  { q: 'Ratio of 3:4, if total 140, larger part?', a: '80', opts: ['80', '60', '70', '100'], category: 'aptitude' },
  { q: 'Average of 10,20,30,40,50 is?', a: '30', opts: ['30', '25', '35', '40'], category: 'aptitude' },
  { q: 'If 6x - 8 = 10, what is 3x?', a: '9', opts: ['9', '3', '6', '12'], category: 'aptitude' },
  { q: 'Percentage increase 50 to 75?', a: '50%', opts: ['50%', '25%', '75%', '60%'], category: 'aptitude' },
  { q: 'If x² = 81, what is x?', a: '9', opts: ['9', '3', '27', '81'], category: 'aptitude' },
  { q: 'Work done by A in 5 hrs = B in 10hrs. Ratio?', a: '2:1', opts: ['2:1', '1:2', '5:10', '10:5'], category: 'aptitude' },
  { q: 'If angle A = 60°, angle B = 2A, B is?', a: '120°', opts: ['120°', '30°', '60°', '90°'], category: 'aptitude' },
  { q: 'Diagonal of square with side 5?', a: '5√2', opts: ['5√2', '10', '5', '25'], category: 'aptitude' },
  { q: 'If x + y = 10 and x - y = 4, x?', a: '7', opts: ['7', '3', '6', '4'], category: 'aptitude' },
  { q: 'Volume of cube with edge 3?', a: '27', opts: ['27', '9', '18', '36'], category: 'aptitude' },
  { q: 'Discount 30% on $200 leaves?', a: '$140', opts: ['$140', '$170', '$60', '$230'], category: 'aptitude' },
  { q: 'If √x = 5, what is x?', a: '25', opts: ['25', '5', '10', '2.5'], category: 'aptitude' },

  // HARD - REASONING (25 questions)
  { q: 'All square are rectangles. Rectangle square?', a: 'No', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'If neither A nor B is true, A or B?', a: 'False', opts: ['True', 'False', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'All prime greater than 2 are odd. 7 is prime?', a: 'Yes', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'No even number is odd. 4 is odd?', a: 'No', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'If A implies B and B implies C, A implies C?', a: 'Yes', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'Some poets are writers. Some writers famous?', a: 'Cannot determine', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'All cats animals. Some animals wild?', a: 'Cannot determine', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'If P and Q both true, not P is?', a: 'False', opts: ['True', 'False', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'No liquid is solid. Gas not solid?', a: 'Cannot determine', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'All roses are flowers. Daisy flower?', a: 'Cannot determine', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'If A true and B false, A and B?', a: 'False', opts: ['True', 'False', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'Either X or Y is true. X true then Y?', a: 'False', opts: ['True', 'False', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'Some leaders brilliant. All brilliant successful?', a: 'Cannot determine', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'If not A implies not B, A true means B?', a: 'Cannot determine', opts: ['Must be true', 'Must be false', 'Cannot determine', 'Maybe true'], category: 'reasoning' },
  { q: 'All metals conduct electricity. Copper conducts?', a: 'Yes', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'No vertebrate is invertebrate. Snake vertebrate?', a: 'Yes', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'Some clouds bring rain. Clouds bring water?', a: 'Cannot determine', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'If X and Y, then Z. Z false means?', a: 'X or Y false', opts: ['Both true', 'Both false', 'X or Y false', 'Cannot tell'], category: 'reasoning' },
  { q: 'All lawyers have degree. Graduated person lawyer?', a: 'No', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'Some athletes dedicate. All dedicated win?', a: 'Cannot determine', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'Not A or Not B means A and B?', a: 'False', opts: ['True', 'False', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'All honest are trusted. Trusted person honest?', a: 'No', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'If A then B. Not B means not A?', a: 'Yes', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'Some fruits sweet. All sweet delicious?', a: 'Cannot determine', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },
  { q: 'All birds have wings. Can fly means bird?', a: 'No', opts: ['Yes', 'No', 'Cannot determine', 'Maybe'], category: 'reasoning' },

  // HARD - BOOLEAN LOGIC
  { q: 'Value of: !(A && B) == (!A || !B)', a: 'true', opts: ['true', 'false', 'depends', 'error'], category: 'boolean-logic' },
  { q: 'If A=true, B=false, C=true. Value of: (A && B) || (C && !B)', a: 'true', opts: ['true', 'false', 'A', 'null'], category: 'boolean-logic' },
  { q: 'Result of: !!undefined || "Data"', a: 'Data', opts: ['true', 'false', 'Data', 'undefined'], category: 'boolean-logic' },
  { q: 'Result of: (true || false) && (false || true) && !false', a: 'true', opts: ['true', 'false', 'error', 'null'], category: 'boolean-logic' },

  // HARD - ALGORITHMIC LOGIC
  { q: 'Recursive: F(0)=1, F(n)=n*F(n-1). What is F(3)?', a: '6', opts: ['3', '6', '9', '2'], category: 'algorithmic-logic' },
  { q: 'X=1. For i=1 to 4: If i%2==0: X=X*2 else: X=X+1. Final X?', a: '6', opts: ['4', '6', '8', '10'], category: 'algorithmic-logic' },
  { q: 'Process: A=1, B=2. Loop 3x: { A=A+B, B=A-B }. Final A?', a: '8', opts: ['5', '8', '13', '3'], category: 'algorithmic-logic' },
  { q: 'Constraint: A must sit next to B. C cannot sit next to A. If B is in seat 2, where is A?', a: '1 or 3', opts: ['1 or 3', 'Only 1', 'Only 3', 'Cannot sit'], category: 'reasoning' },
  { q: 'Logic: Only one statement is true. 1: A is a liar. 2: B is a liar. 3: Neither are liars. Who is honest?', a: 'Cannot determine', opts: ['A', 'B', 'Neither', 'Cannot determine'], category: 'reasoning' }
];

// Build comprehensive question bank
const questionBank = {
  easy: easyQuestions,
  medium: mediumQuestions,
  hard: hardQuestions,
  getAllByDifficulty: (difficulty) => {
    if (difficulty === 'easy') return easyQuestions;
    if (difficulty === 'medium') return mediumQuestions;
    if (difficulty === 'hard') return hardQuestions;
    return [];
  },
  getByCategory: (category, difficulty) => {
    let questions = [];
    if (difficulty === 'easy') questions = easyQuestions;
    else if (difficulty === 'medium') questions = mediumQuestions;
    else if (difficulty === 'hard') questions = hardQuestions;
    return questions.filter(q => q.category === category);
  }
};

module.exports = questionBank;
