import React, { useState, useEffect } from 'react';
import { generateQuestion } from '../services/aiService';
import { submitAnswer } from '../services/questionService';
import { getHint, getExplanation } from '../services/aiService';
import LoadingSpinner from '../components/LoadingSpinner';
import ErrorMessage from '../components/ErrorMessage';
import { FaLightbulb, FaRedo, FaTrash } from 'react-icons/fa';
import { getCategoryName } from '../utils/formatters';
import './Practice.css';

/**
 * Practice Page - AI-generated questions
 */
const Practice = () => {
    const [category, setCategory] = useState('number-series');
    const [difficulty, setDifficulty] = useState('easy');
    const [question, setQuestion] = useState(null);
    const [selectedAnswer, setSelectedAnswer] = useState('');
    const [showResult, setShowResult] = useState(false);
    const [result, setResult] = useState(null);
    const [hint, setHint] = useState('');
    const [explanation, setExplanation] = useState('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');
    const [autoGenerate, setAutoGenerate] = useState(true);
    const [autoGenerateDelay, setAutoGenerateDelay] = useState(3);
    const [viewedQuestions, setViewedQuestions] = useState([]);
    const [totalQuestionsGenerated, setTotalQuestionsGenerated] = useState(0);
    const [timer, setTimer] = useState(null);
    const [countdown, setCountdown] = useState(0);

    // Load viewed questions from localStorage on mount
    useEffect(() => {
        const saved = localStorage.getItem('practiceViewedQuestions');
        if (saved) {
            try {
                setViewedQuestions(JSON.parse(saved));
            } catch (e) {
                console.error('Failed to load viewed questions:', e);
            }
        }
    }, []);

    // Save viewed questions to localStorage whenever they change
    useEffect(() => {
        localStorage.setItem('practiceViewedQuestions', JSON.stringify(viewedQuestions));
    }, [viewedQuestions]);

    // Cleanup timer on unmount
    useEffect(() => {
        return () => {
            if (timer) clearTimeout(timer);
        };
    }, [timer]);

    // Handle countdown for auto-generate
    useEffect(() => {
        let interval;
        if (countdown > 0) {
            interval = setInterval(() => {
                setCountdown(prev => prev - 1);
            }, 1000);
        }
        return () => clearInterval(interval);
    }, [countdown]);

    const categories = [
        { value: 'number-series', label: 'Number Series' },
        { value: 'patterns', label: 'Patterns' },
        { value: 'puzzles', label: 'Puzzles' },
        { value: 'aptitude', label: 'Aptitude' },
        { value: 'reasoning', label: 'Reasoning' }
    ];

    const difficulties = [
        { value: 'easy', label: 'Easy' },
        { value: 'medium', label: 'Medium' },
        { value: 'hard', label: 'Hard' }
    ];

    const handleResetQuestions = () => {
        if (window.confirm('Clear all viewed questions? You can practice with the same questions again.')) {
            setViewedQuestions([]);
            localStorage.removeItem('practiceViewedQuestions');
            setTotalQuestionsGenerated(0);
            setQuestion(null);
            setError('Viewed questions cleared! You can now see repeated questions.');
        }
    };

    const handleGenerateQuestion = async () => {
        setError('');
        setLoading(true);
        setQuestion(null);
        setSelectedAnswer('');
        setShowResult(false);
        setHint('');
        setExplanation('');

        try {
            const response = await generateQuestion(category, difficulty, viewedQuestions);
            setQuestion(response.data);
            setViewedQuestions([...viewedQuestions, response.data._id]);
            setTotalQuestionsGenerated(totalQuestionsGenerated + 1);
        } catch (err) {
            setError(err.response?.data?.message || 'Failed to generate question. Please try again.');
        } finally {
            setLoading(false);
        }
    };

    const handleGetHint = async () => {
        if (!question) return;

        setLoading(true);
        try {
            const response = await getHint(question._id);
            setHint(response.data.hint);
        } catch (err) {
            setError('Failed to get hint');
        } finally {
            setLoading(false);
        }
    };

    const handleSubmitAnswer = async () => {
        if (!selectedAnswer) {
            setError('Please select an answer');
            return;
        }

        setLoading(true);
        try {
            const response = await submitAnswer(question._id, selectedAnswer);
            setResult(response.data);
            setShowResult(true);

            // Get AI explanation
            const explainResponse = await getExplanation(question._id, selectedAnswer);
            setExplanation(explainResponse.data.explanation);

            // Auto-generate next question after delay
            if (autoGenerate) {
                setCountdown(autoGenerateDelay);
                const newTimer = setTimeout(() => {
                    handleGenerateQuestion();
                    setTimer(null);
                    setCountdown(0);
                }, autoGenerateDelay * 1000);
                setTimer(newTimer);
            }
        } catch (err) {
            setError('Failed to submit answer');
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="practice-page">
            <div className="container">
                <div className="practice-header fade-in">
                    <h1>Practice Mode</h1>
                    <p>Challenge yourself with AI-generated logic questions</p>
                </div>

                {/* Settings */}
                <div className="practice-settings card">
                    <div className="settings-row">
                        <div className="input-group">
                            <label>Category</label>
                            <select value={category} onChange={(e) => setCategory(e.target.value)}>
                                {categories.map(cat => (
                                    <option key={cat.value} value={cat.value}>{cat.label}</option>
                                ))}
                            </select>
                        </div>

                        <div className="input-group">
                            <label>Difficulty</label>
                            <select value={difficulty} onChange={(e) => setDifficulty(e.target.value)}>
                                {difficulties.map(diff => (
                                    <option key={diff.value} value={diff.value}>{diff.label}</option>
                                ))}
                            </select>
                        </div>

                        <div className="input-group">
                            <label>
                                <input
                                    type="checkbox"
                                    checked={autoGenerate}
                                    onChange={(e) => setAutoGenerate(e.target.checked)}
                                />
                                Auto-generate next question
                            </label>
                        </div>

                        {autoGenerate && (
                            <div className="input-group">
                                <label>Delay (seconds): {autoGenerateDelay}s</label>
                                <input
                                    type="range"
                                    min="1"
                                    max="10"
                                    value={autoGenerateDelay}
                                    onChange={(e) => setAutoGenerateDelay(Number(e.target.value))}
                                />
                            </div>
                        )}

                        <button
                            onClick={() => {
                                if (timer) clearTimeout(timer);
                                setTimer(null);
                                setCountdown(0);
                                handleGenerateQuestion();
                            }}
                            className="btn btn-primary"
                            disabled={loading}
                        >
                            <FaRedo /> {question ? 'New Question' : 'Generate Question'}
                        </button>

                        {viewedQuestions.length > 0 && (
                            <button onClick={handleResetQuestions} className="btn btn-outline btn-danger" title="Clear viewed questions history">
                                <FaTrash /> Reset ({viewedQuestions.length})
                            </button>
                        )}
                    </div>
                </div>

                <ErrorMessage message={error} onClose={() => setError('')} />

                {loading && !question && <LoadingSpinner message="Generating question..." />}

                {/* Question Display */}
                {question && (
                    <div className="question-card card fade-in">
                        <div className="question-meta">
                            <span className="badge badge-primary">{getCategoryName(category)}</span>
                            <span className={`badge badge-${difficulty}`}>{difficulty}</span>
                            <span className="points">{question.points} points</span>
                            <span className="question-counter">Question #{totalQuestionsGenerated}</span>
                        </div>

                        <h2 className="question-text">{question.questionText}</h2>

                        <div className="options-list">
                            {question.options.map((option, index) => (
                                <div
                                    key={index}
                                    className={`option-item ${selectedAnswer === option ? 'selected' : ''} ${showResult ? (option === result.correctAnswer ? 'correct' : selectedAnswer === option ? 'incorrect' : '') : ''
                                        }`}
                                    onClick={() => !showResult && setSelectedAnswer(option)}
                                >
                                    <span className="option-label">{String.fromCharCode(65 + index)}</span>
                                    <span className="option-text">{option}</span>
                                </div>
                            ))}
                        </div>

                        {!showResult && (
                            <div className="question-actions">
                                <button onClick={handleGetHint} className="btn btn-outline" disabled={loading}>
                                    <FaLightbulb /> Get Hint
                                </button>
                                <button onClick={handleSubmitAnswer} className="btn btn-primary" disabled={!selectedAnswer || loading}>
                                    Submit Answer
                                </button>
                            </div>
                        )}

                        {/* Hint */}
                        {hint && !showResult && (
                            <div className="hint-box">
                                <h4><FaLightbulb /> Hint:</h4>
                                <p>{hint}</p>
                            </div>
                        )}

                        {/* Result */}
                        {showResult && (
                            <div className={`result-box ${result.isCorrect ? 'correct' : 'incorrect'}`}>
                                <h3>{result.isCorrect ? '✓ Correct!' : '✗ Incorrect'}</h3>
                                {result.isCorrect && <p>You earned {result.pointsEarned} points!</p>}
                                {!result.isCorrect && <p>The correct answer was: {result.correctAnswer}</p>}

                                {explanation && (
                                    <div className="explanation-box">
                                        <h4>Explanation:</h4>
                                        <p>{explanation}</p>
                                    </div>
                                )}

                                {autoGenerate && (
                                    <p className="auto-generate-notice">
                                        <span className="spinner"></span> Next question loading in {countdown}s...
                                    </p>
                                )}

                                {!autoGenerate && (
                                    <button onClick={handleGenerateQuestion} className="btn btn-primary mt-md">
                                        <FaRedo /> Try Another Question
                                    </button>
                                )}
                            </div>
                        )}
                    </div>
                )}

                {!question && !loading && (
                    <div className="empty-state card text-center">
                        <h3>Ready to Practice?</h3>
                        <p>Select a category and difficulty level, then generate a question to get started!</p>
                    </div>
                )}
            </div>
        </div>
    );
};

export default Practice;
